### ISSUE TITLE
[Help] Lazy Loading Option

### ISSUE THREAD

**Issue by cs-mshah** [Mocca101/obsidian-plugin-groups#15]
How do we lazy load a particular group?

**Comment by cs-mshah** [comment]
Found it. We need to click on the `Load on startup button`.  Maybe this could be added to the README.

Also, I checked the startup times and they got increased. Lazy loading doesn't seem to work.

**Comment by hustrjh** [comment]
Hi, @cs-mshah. If you wanna lazy loading works, you need to disable the plugins manually first.

As you enable the plugins before, they are written in **`.obsidian/community-plugins.json`** which means Obsidian will load the plugins automatically. That's why lazy loading seems not to work. After you disable the plugins manually, **`community-plugins.json`** will get rid of the plugins and then **`Plugin Groups`** works.

I hope this could help you. This is a wonderful plugin.

Also I hope @Mocca101 could mention this in `Readme`. Many people would encounter the same problem.

**Comment by Mocca101** [comment]
Ah yes, thank you I'll update the README to clarify that!

**Comment by hustrjh** [comment]
Correct and thorough. :+1:
